import json, requests

payload = {"message":"81736","texte":"à l'attention de l'équipe BC - chaine d'mport transport IN1 bloquée Bonjour,\r\n\r\nLa chaîne d'import des OT vers IN1, automatisé pour des transport toutes les heures, est bloqué depuis vendredi dernier visiblement.\r\nLe 1er OT de la liste ressort effectivement en code retour 12, mais je ne vois pas pourquoi cela bloque la liste.\r\nJ'ai pu forcer l'import manuellement d'un OT (DE2K914366) mais il reste dans la liste même en actualisant.\r\n\r\nSeuls 5 OT apparaissent dans la liste et nous ne pouvons transporter ceux libérés qui apparaissent en dessous (cf. capture ci-jointe).\r\nPouvez-vous résoudre le problème\r\n\r\nN'hésitez pas si je ne suis pas claire.\r\nMerci d'avance\r\n\r\nCaroline MASSÉ\r\nBonjour,\r\n\r\nVotre demande a bien été prise en compte et transmise à notre équipe de consultants qui la traitera dans les meilleurs délais.\r\n\r\nCordialement,\r\n\r\nJulien MROZEK - Dispatcheur PasàPas\r\nPASàPAS - 51 rue Saint-Georges 75009 PARIS\r\nT : 09 72 501 501\r\nMail : julien.mrozek@pasapas.com\r\nAnalyse et appelle Caroline pour voir ensemble le problème.\r\nBonjour Caroline,\r\n\r\nComme vu par téléphone, l'import de l'OT DE1K914386 se termine avec un code retour 8 avec le message\r\n\r\nR3TRTABLZWRT_POSPRISTS original object cannot be replaced\r\n\r\net  code retour 12 avec le message\r\n\r\nLIMU TABD ZWRT_POSPRISTS: Object information could not be imported\r\n\r\nL'OT DE1K914386 a été importé manuellement avec l'option 'Overwrite Originals\" et a été supprimé de la file d'import ainsi que l'OT DE1K914366.\r\n\r\nLe job de transport a été déclenché pour vérifier que les autres OTs se transportent correctement.\r\n\r\nPendant l’exécution du job le 'End Mark' a été supprimé automatiquement et l'ensemble des OTs sont maintenant visible.\r\n\r\nL'OT DE1K914259 est tombé en erreur (Syntax error) du coup les autres transports sont bloqués.\r\n\r\nAu niveau de la configuration,de la STMS vous avec les paramètres  qui explique le comportement ;\r\n\r\nREPEATONERROR = 8\r\nSTOPONERROR = 9\r\n\r\nSi un OT génère un code retour > à 9 l'import s'arrête.\r\n\r\nSi vous avez besoin de plus de précisions, n'hésitez pas à revenir vers moi.\r\n\r\nCordialement,\r\nDahlia.\r\n\r\nTel : 06 33 60 64 65\r\nBonjour Dahlia,\r\n\r\nMerci pour votre retour.\r\nL'OT DE1K914259 qui est en erreur est en analyse par son titulaire.\r\n\r\nLes OT suivants dans la liste ainsi que ceux libérés depuis sont passés via le transport planifié de 12h00 sans soucis.\r\nJe clôture donc la demande.\r\n\r\nCordialement,\r\nCaroline"}
url = "http://localhost:5000/tfidf_classic/"
headers = {'Content-type': 'application/json', 'Accept': 'text/plain', 'Referer': url}
r= requests.post(url, data=json.dumps(payload), headers=headers)

result = r.json()

print(result)